### ISSUE TITLE
App will not compile - missing .dll's. // Need some help

### ISSUE THREAD

**Issue by mfuriate** [UXDivers/Grial-UI-Kit-Support#251]
I have purchased and downloaded the Grail UI kit and I am having nothing but trouble so far. I am missing the UXDrivers.Artina, and all variants of Artina .dlls, and the apps will not compile. I have tried to use the github repository and it fails every time when trying to resolve the dependencies. Can you please give me a link to download the .dll files directly and I will add them to my application manually and change the referenced path. Thank you.

**Comment by jpbrocca** [comment]
Hi @mfuriate,

Did you check the documentation about downloading Grial and Configuring nugget packages source? This last step is crucial to get access to dlls:

http://uxdivers.github.io/Grial-UI-Kit-Support/#-downloading-grial

http://uxdivers.github.io/Grial-UI-Kit-Support/#-grial-first-run

Hope that helps!
JP

**Comment by mfuriate** [comment]
Support,

 

I have followed the guides meticulously and I am still not having any luck. The Nuget references will not resolve properly and thus will not download. 

 

The other .dll’s have local / relative references and can be found in one of the application directories. Why do you not include the Artina .dll’s here too? This is a huge waste of time when the solution should arrive complete with all the resources required. I have devoted 3 days to messing around with this. I simply want it to work, which I am confident it will do.

 

Your help is appreciated. Thank you.

 

 

 



 

 

Please call / email with any questions or comments.

   Nextech Logo

Mark A. Furiate

CTO / Principal

Nextech – Business Technology Management, LLC.

2928 Saddlebrook Drive

Findlay, Ohio 45840

Email: mfuriate@nex-tech.biz

Phone: 419.306.3078

 

PRIVILEGE AND CONFIDENTIALITY NOTICE: The information contained in this e-mail communication and any attached documentation may be privileged, confidential or otherwise protected from disclosure and is intended only for the use of the designated recipient(s). If the reader or recipient of this communication is not the intended recipient, or an employee or agent of the intended recipient who is responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution, copying or other use of this communication is strictly prohibited. If you have received this communication in error, please immediately notify us by return e-mail and promptly delete the original electronic e-mail communication and any attached documentation. Receipt by anyone other than the intended recipient is not a waiver of any attorney-client or work-product privilege.

**Comment by LeoHere** [comment]
Hi @mfuriate, assemblies should be pulled automatically from the Nuget private source once it is properly configured. So we need to figure out what is the problem there before proceeding. 

We can send you the nuget packages so you restore them locally, but that would not be a real solution since you will not get any updates.

- Can you please provide me more details about your environment? Mac/Win using XS, VSMac/VS? 
- Did you get stuck while configuring the nuget source? Can you describe the steps you followed in order configure it and when did you get stuck? I checked the server logs an I can't found any attempt (successful or not) of login from your account.

**Comment by mfuriate** [comment]
Leonardo,

 

Thank you for the reply. I followed your guides meticulously and I am certain that I have not missed anything. I have repeated the process multiple times with the same results. I also spent time in the community threads and looking online for a resolution before contacting you. While I did see a lot of others with the same problem, I did not find a satisfactory solution.

 

Environment

·         Windows 10 Pro (fully patched)

·         Visual Studio 2017 (fully patched)

·         Xamarin (fully patched)

 

The screenshot that I sent you really tells the whole story. I have entered your path for Nuget source (http://nuget.uxdrivers.com/grail) . When I run “Restore” it fails to find the source files producing the error (“An error occurred while trying to restore the packages: Unable to find version ‘2.0.60’ of package ‘UXDrivers.Artina.Shared’. Every other referenced library is fully resolved and without error including “UXDrivers.Effects”. 

 

The specific libraries that are not resolving are: 

·         Portable Class Library

o   UXDrivers.Artina.Shared

o   UXDrivers.Artina.Shared.Base

·         Android

o   UXDrivers.Artina.Shared

o   UXDrivers.Artina.Shared.Base

o   UXDrivers.Artina.Shared.Droid

o   UXDrivers.Artina.Shared.Base.Droid

·         iOS

o   UXDrivers.Artina.Shared

o   UXDrivers.Artina.Shared.Base

o   UXDrivers.Artina.Shared.iOS

o   UXDrivers.Artina.Shared.Base.iOS

 

I agree that I would like to find the underlying cause of the problem and I hope that you can help me do that. In the meanwhile, I need to move forward with development on this project. I have already devoted nearly a week to resolving this issue. Can you please forward the .dll’s that are missing ASAP and then we can work out the broader issue of why the Nuget packages are not resolving. 

 

Thank you for your assistance. 

 

Please call / email with any questions or comments.

   Nextech Logo

Mark A. Furiate

CTO / Principal

Nextech – Business Technology Management, LLC.

2928 Saddlebrook Drive

Findlay, Ohio 45840

Email: mfuriate@nex-tech.biz

Phone: 419.306.3078

 

PRIVILEGE AND CONFIDENTIALITY NOTICE: The information contained in this e-mail communication and any attached documentation may be privileged, confidential or otherwise protected from disclosure and is intended only for the use of the designated recipient(s). If the reader or recipient of this communication is not the intended recipient, or an employee or agent of the intended recipient who is responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution, copying or other use of this communication is strictly prohibited. If you have received this communication in error, please immediately notify us by return e-mail and promptly delete the original electronic e-mail communication and any attached documentation. Receipt by anyone other than the intended recipient is not a waiver of any attorney-client or work-product privilege.

**Comment by LeoHere** [comment]
@mfuriate thanks for the detailed explanation.

Where did you get this `http://nuget.uxdrivers.com/grail` from? It is wrong, it has an extra `r`, it is **uxdivers** not **uxdrivers**. The correct url is [http://nuget.uxdivers.com/grail](http://nuget.uxdivers.com/grail).

Please try again with the correct URL and let me know how it goes. It will ask for your credentials (the same you use in Grial Admin).

This process should not be painful at all. Also, please let us know where you get the URL from so we can correct this if it is on our side.

**Comment by jpbrocca** [comment]
Hi @mfuriate,
It seems you are replying through email to the github notifications. Even while that will sync your text with this thread images are not attached.

Can you add your image on within issue directly?
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/251#issuecomment-330832646

Just in case, I noticed you used this url:

http://nuget.uxdrivers.com/grail

Which is wrong and that could be causing your issue.

Best,
JP

**Comment by mfuriate** [comment]
![image](https://user-images.githubusercontent.com/23586528/30643981-dc8fee8a-9dde-11e7-8bbb-1f0c1c5b1565.png)

**Comment by mfuriate** [comment]
I have uploaded the screen shot in the thread. The URL was a typo, You will note that I am using the correct URL and still not resolving. Thanks.

 

 

Please call / email with any questions or comments.

   Nextech Logo

Mark A. Furiate

CTO / Principal

Nextech – Business Technology Management, LLC.

2928 Saddlebrook Drive

Findlay, Ohio 45840

Email: mfuriate@nex-tech.biz

Phone: 419.306.3078

 

PRIVILEGE AND CONFIDENTIALITY NOTICE: The information contained in this e-mail communication and any attached documentation may be privileged, confidential or otherwise protected from disclosure and is intended only for the use of the designated recipient(s). If the reader or recipient of this communication is not the intended recipient, or an employee or agent of the intended recipient who is responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution, copying or other use of this communication is strictly prohibited. If you have received this communication in error, please immediately notify us by return e-mail and promptly delete the original electronic e-mail communication and any attached documentation. Receipt by anyone other than the intended recipient is not a waiver of any attorney-client or work-product privilege.

**Comment by LeoHere** [comment]
@mfuriate omg...it was a double typo the **grail** should be **grial**. In my last post I corrected the first issue but not the second one :(

I already corrected this second typo it in my last post, the correct URL is [http://nuget.uxdivers.com/grial/](http://nuget.uxdivers.com/grial/).

We will add it as plain text in the documentation so anyone can copy&paste it and we avoid this kind of issues.

I hope this time you succeeded restoring the packages.

**Comment by jpbrocca** [comment]
@mfuriate just in case, in your image you still have a wrong URL:

![image](https://user-images.githubusercontent.com/15996999/30646079-2107260a-9dee-11e7-995f-b03da4dc6744.png)

As @LeoHere mentioned, the URL should be:

http://nuget.uxdivers.com/grial

Best,
JP

**Comment by mfuriate** [comment]
I see now. Why would you play games with the spelling of these resources? It was a typo issue but this is a problem that did need to happen. I am certain that a good number of the others whith problems with your libraries are having the same issue. Take my advice and change them to the correct spelling. You will have a lot less support requests and leave a better impression. Thank you.

 

 

Please call / email with any questions or comments.

   Nextech Logo

Mark A. Furiate

CTO / Principal

Nextech – Business Technology Management, LLC.

2928 Saddlebrook Drive

Findlay, Ohio 45840

Email: mfuriate@nex-tech.biz

Phone: 419.306.3078

 

PRIVILEGE AND CONFIDENTIALITY NOTICE: The information contained in this e-mail communication and any attached documentation may be privileged, confidential or otherwise protected from disclosure and is intended only for the use of the designated recipient(s). If the reader or recipient of this communication is not the intended recipient, or an employee or agent of the intended recipient who is responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution, copying or other use of this communication is strictly prohibited. If you have received this communication in error, please immediately notify us by return e-mail and promptly delete the original electronic e-mail communication and any attached documentation. Receipt by anyone other than the intended recipient is not a waiver of any attorney-client or work-product privilege.

**Comment by jpbrocca** [comment]
Hi @mfuriate, thanks for your suggestion.

We are not playing games with our customers.
The name of our company is just **UXDivers** and our product is called **Grial** hence the URL.
You are right that this should be easier, we will add this to the URL so users can copy and paste and avoid these issues.

Thanks for helping us to notice this issue, and I am truly sorry about it.

Best,
JP

**Comment by mfuriate** [comment]
Challenges aside, thank you for your assistance. 

 

 

Please call / email with any questions or comments.

   Nextech Logo

Mark A. Furiate

CTO / Principal

Nextech – Business Technology Management, LLC.

2928 Saddlebrook Drive

Findlay, Ohio 45840

Email: mfuriate@nex-tech.biz

Phone: 419.306.3078

 

PRIVILEGE AND CONFIDENTIALITY NOTICE: The information contained in this e-mail communication and any attached documentation may be privileged, confidential or otherwise protected from disclosure and is intended only for the use of the designated recipient(s). If the reader or recipient of this communication is not the intended recipient, or an employee or agent of the intended recipient who is responsible for delivering it to the intended recipient, you are hereby notified that any review, dissemination, distribution, copying or other use of this communication is strictly prohibited. If you have received this communication in error, please immediately notify us by return e-mail and promptly delete the original electronic e-mail communication and any attached documentation. Receipt by anyone other than the intended recipient is not a waiver of any attorney-client or work-product privilege.

**Comment by jpbrocca** [comment]
Oh, no, thank you for pointing this issue and for your patience.
I have just updated the docs to include the URL :)

Best,
JP


Best,
JP

**Comment by LeoHere** [comment]
Closing the issue. Feel free to open it again if you need to.

**Comment by szaid07** [comment]
I am getting Response status code does not indicate success: 401.

**Comment by edouardRego** [comment]
Hi everyone,
I would like to ask something, I try to create an app with different themes. Fo that I have my grial link and I could install grial nugget but I it's missing a nuget, UXDivers.Artina.Grial no? If I want to change different themes in my app I need to have this nuget isn't it?

Thank you for your replies.

**Comment by LeoHere** [comment]
@edouardRego `UXDivers.Artina.Grial` is not a Nuget package. Changing themes is as easy as swapping a resource dictionary. Please read [this](https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-theme-and-branding-of-your-app) for a full explanation of how theming works.

Hope it helps.

**Comment by Vikas-jk** [comment]
Hello, I am using .NET MAUI Kit and I was trying to set up my Visual Studio with Nuget package as mentioned
https://docs.grialkit.com/grial-web-admin/nuget-setup

But when I enter Nuget package url with username/password, it is not connecting and getting 401 unauthorized error

`The V2 feed at 'https://nuget.uxdivers.com/grial/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='net8.0-android34.0%7Cnet8.0-ios17.2%7Cnet8.0-maccatalyst17.2%7Cnet8.0-windows10.0.19041'&includePrerelease=false&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.`

Above is the Error which I can see in Visual Studio output.

I have tried saving/editing correct username/password but it doesn't work.

Even if I type in url in browser "https://nuget.uxdivers.com/grial/" and try to enter credentials, it doesn't login.

What could be wrong here?
Does it takes time to enable nuget dedicated user?

Or Do I need to purchase license first? then only I can use it even for demo purpose?
