### ISSUE TITLE
ThemeColors.cs is not auto generated in netstandard project(?)

### ISSUE THREAD

**Issue by RocketPop** [UXDivers/Grial-UI-Kit-Support#503]
### Description

I added grial to an existing netstandard2.0 project. ThemeColors.cs and Colors.xml do not regenerate when modifying my theme. The include for the grial build targets was not in my .csproj - The "full" sample does update and I noticed that this directive:
``` 
<Import Project="..\packages\UXDivers.Artina.Shared.2.7.1\build\netstandard1.0\UXDivers.Artina.Shared.targets" Condition="Exists('..\packages\UXDivers.Artina.Shared.2.7.1\build\netstandard1.0\UXDivers.Artina.Shared.targets')" />
```
was not in my project. I added it and that doesn't seem to change anything. The theme is marked as EmbeddedResource and has MSBuild:UpdateDesignTimeXaml set... I'm not sure how to connect the theme xaml to the custom build step. I put a themes.json file in there too but no effect. I can't start with your template project - I have too much existing code and libs etc. (it's all netstandard too). Edit: I have custom renderers etc. just fine so Grial is "working", just not this build step.

 I'd be ok with a manual workaround if I can run that build step "by hand".

### Steps to Reproduce

1. Make a complicated netstandard app 
2. Add Grial to it "manually"
3. ThemeColors doesn't update 😀 

### Expected Behavior

Changes in the theme colors should be reflected in ThemeColors.cs

### Actual Behavior

It's not re-generated

### Basic Information

- Version with issue: 2.7
- Last known good version: unknown
- IDE: Visual Studio 2017 Enterprise 
- Platform Target Frameworks: Latest xamarin
- Nuget Packages: lots
- Affected Devices: iOS build process

### Screenshots

n/a

**Comment by LeoHere** [comment]
@RocketPop loved the "Step to Reproduce" section of your report, specially step 1. 

😀

Please do a build and look for `[Grial]` or `PropagateThemeTask` or `GrialTheme` in the build output. Paste your findings here.

Here is an example of what you should be looking for...
~~~
Target GrialTheme:
  Using "PropagateThemeTask" task from assembly "....UXDivers.Artina.Shared.2.7.5/build/netstandard1.0/UXDivers.Grial.Build.Tasks.dll".
  Task "PropagateThemeTask"
    [Grial] Initiating Syncrhonization for project '....source/Droid/Grial.Droid.csproj'. Any Theme sync issues will be reported as a Build Warning. 
    No settings found at '....source/Droid/Themes.json'
    Project '....source/Droid/Grial.Droid.csproj' was recognized as an Android Project.
    Initiating App.xaml lookup.
    App.xaml: ....source/Grial/App.xaml
    App.xaml Project: ....source/Grial/Grial.csproj
    Analyzing App.xaml, looking for the current Theme.
    Assuming Grial Theme is the first resource dictionary named 'local:GrialLightTheme'.
    Initiating Theme XAML file definition x:Class='UXDivers.Artina.Grial.GrialLightTheme'.
    Resolving Theme across all XAMLs.
    Found Theme XAML file at '....source/Grial/Themes/GrialLightTheme.xaml'.
    Loaded theme colors from '....source/Grial/Themes/GrialLightTheme.xaml'.
    Android theme color synchronization completed (....source/Droid/Resources/values/Colors.xml).
    [Grial] Terminating Syncrhonization
  Done executing task "PropagateThemeTask".
~~~

**Comment by RocketPop** [comment]
Edit: I forgot to turn my logging up. I do see:
```
2>Target "GrialTheme" in file "D:\Dev\TruckBudsProject\TruckBudsApp\packages\UXDivers.Artina.Shared.2.7.1\build\netstandard1.0\UXDivers.Artina.Shared.targets" from project "D:\Dev\TruckBudsProject\TruckBudsApp\TruckBudsApp.iOS\TruckBudsApp.iOS.csproj" (target "Build" depends on it):
2>Using "PropagateThemeTask" task from assembly "C:\Users\wilks_000\.nuget\packages\uxdivers.artina.shared\2.7.5\build\netstandard1.0\UXDivers.Grial.Build.Tasks.dll".
2>Task "PropagateThemeTask"
2>  [Grial] Initiating Syncrhonization for project 'D:\Dev\TruckBudsProject\TruckBudsApp\TruckBudsApp.iOS\TruckBudsApp.iOS.csproj'. Any Theme sync issues will be reported as a Build Warning. 
2>  No settings found at 'D:\Dev\TruckBudsProject\TruckBudsApp\TruckBudsApp.iOS\Themes.json'
2>  Project 'D:\Dev\TruckBudsProject\TruckBudsApp\TruckBudsApp.iOS\TruckBudsApp.iOS.csproj' was recognized as an iOS Project.
2>  Initiating App.xaml lookup.
2>  [Error] 'Error 'Object reference not set to an instance of an object.' ocurred while analyzing Grial theme usage'. Exception message 'Object reference not set to an instance of an object.'. StackTrace: '   at UXDivers.Daas.Engine.ProjectItemsImpl.LoadProjectItems()
2>     at UXDivers.Daas.Engine.ProjectImpl.LoadProjectItems()
2>     at UXDivers.Daas.Engine.ProjectItemsImpl.GetFileByPath(String path, Boolean caseSensitive)
2>     at UXDivers.Daas.Commands.GrialAnalyzeSolutionCommand.FindAppXaml(IProjectItems project, IXamlManager xamlManager)
2>     at UXDivers.Daas.Commands.GrialAnalyzeSolutionCommand.Execute(IExecutionContext ctx)'
2>  [Grial] Terminating Syncrhonization
2>Done executing task "PropagateThemeTask".
```
Perhaps can't parse the .csproj in the new format?

**Comment by RocketPop** [comment]
I tried with a Themes.json file as well which fails with: 

```3>Target "GrialTheme" in file "D:\Dev\MyProject\MyProjectApp\packages\UXDivers.Artina.Shared.2.7.1\build\netstandard1.0\UXDivers.Artina.Shared.targets" from project "D:\Dev\MyProject\MyProjectApp\MyProjectApp.iOS\MyProjectApp.iOS.csproj" (target "Build" depends on it):
3>Using "PropagateThemeTask" task from assembly "C:\Users\wilks_000\.nuget\packages\uxdivers.artina.shared\2.7.5\build\netstandard1.0\UXDivers.Grial.Build.Tasks.dll".
3>Task "PropagateThemeTask"
3>  [Grial] Initiating Syncrhonization for project 'D:\Dev\MyProject\MyProjectApp\MyProjectApp.iOS\MyProjectApp.iOS.csproj'. Any Theme sync issues will be reported as a Build Warning. 
3>  Loading Settings from 'D:\Dev\MyProject\MyProjectApp\MyProjectApp.iOS\Themes.json'
3>   - Importing 'ThemeSyncEnabled' overriding previous value
3>   - AppXamlFullPath was set
3>   - Importing 'iOSColorsFileName' overriding previous value
3>   - Importing 'AndroidColorsFile' overriding previous value
3>   - Importing 'ThemesFolder' overriding previous value
3>  Project 'D:\Dev\MyProject\MyProjectApp\MyProjectApp.iOS\MyProjectApp.iOS.csproj' was recognized as an iOS Project.
3>  Initiating App.xaml lookup.
3>  [Error] 'Error 'Object reference not set to an instance of an object.' ocurred while analyzing Grial theme usage'. Exception message 'Object reference not set to an instance of an object.'. StackTrace: '   at UXDivers.Daas.Engine.ProjectItemsImpl.LoadProjectItems()
3>     at UXDivers.Daas.Engine.ProjectImpl.LoadProjectItems()
3>     at UXDivers.Daas.Engine.ProjectItemsImpl.GetFileByPath(String path, Boolean caseSensitive)
3>     at UXDivers.Daas.Commands.GrialAnalyzeSolutionCommand.FindAppXaml(IProjectItems project, IXamlManager xamlManager)
3>     at UXDivers.Daas.Commands.GrialAnalyzeSolutionCommand.Execute(IExecutionContext ctx)'
3>  [Grial] Terminating Syncrhonization
3>Done executing task "PropagateThemeTask".
3>Done building target "GrialTheme" in project "MyProjectApp.iOS.csproj".
```
In that file, it has hard-coded the absolute path to the App.xaml - perhaps when I have a Themes.json - you don't need to parse the csproj? I'm not sure what that does.

**Comment by LeoHere** [comment]
Hi @RocketPop ,

Try with the following value:

~~~
{
	"AppXamlPath": "<absolute path the the App.xaml>",
	"AppXamlProjectPath": "<absolute path to the .net standard csproj file>",
	"GrialThemePath": "<absolute path to the current theme xaml file>"
} 
~~~

This should skip the lookup of the `App.xaml` and the current `GrialTheme`.

i.e.
~~~
{
	"AppXamlPath": "/Users/Leo/UXDivers/grial/source/Grial/App.xaml",
	"AppXamlProjectPath": "/Users/Leo/UXDivers/grial/source/Grial/Grial.csproj",
	"GrialThemePath": "/Users/Leo/UXDivers/grial/source/Grial/Themes/GrialLightTheme.xaml"
} 
~~~


Please let me know how it goes...

**Comment by RocketPop** [comment]
Hello thanks! Sadly, that gives the same error. I missed GrialThemePath earlier... but still crashes. 

```
3>Target "GrialTheme" in file "D:\Dev\MyProject\MyProjectApp\packages\UXDivers.Artina.Shared.2.7.1\build\netstandard1.0\UXDivers.Artina.Shared.targets" from project "D:\Dev\MyProject\MyProjectApp\MyProjectApp.iOS\MyProjectApp.iOS.csproj" (target "Build" depends on it):
3>Using "PropagateThemeTask" task from assembly "C:\Users\wilks_000\.nuget\packages\uxdivers.artina.shared\2.7.5\build\netstandard1.0\UXDivers.Grial.Build.Tasks.dll".
3>Task "PropagateThemeTask"
3>  [Grial] Initiating Syncrhonization for project 'D:\Dev\MyProject\MyProjectApp\MyProjectApp.iOS\MyProjectApp.iOS.csproj'. Any Theme sync issues will be reported as a Build Warning. 
3>  Loading Settings from 'D:\Dev\MyProject\MyProjectApp\MyProjectApp.iOS\Themes.json'
3>   - Importing 'ThemeSyncEnabled' overriding previous value
3>   - AppXamlFullPath was set
3>   - AppXamlProjectFullPath was set
3>   - GrialThemePath was set
3>   - Importing 'iOSColorsFileName' overriding previous value
3>   - Importing 'AndroidColorsFile' overriding previous value
3>   - Importing 'ThemesFolder' overriding previous value
3>  Project 'D:\Dev\MyProject\MyProjectApp\MyProjectApp.iOS\MyProjectApp.iOS.csproj' was recognized as an iOS Project.
3>  Initiating App.xaml lookup.
3>  [Error] 'Error 'Object reference not set to an instance of an object.' ocurred while analyzing Grial theme usage'. Exception message 'Object reference not set to an instance of an object.'. StackTrace: '   at UXDivers.Daas.Engine.ProjectItemsImpl.LoadProjectItems()
3>     at UXDivers.Daas.Engine.ProjectImpl.LoadProjectItems()
3>     at UXDivers.Daas.Engine.ProjectItemsImpl.GetFileByPath(String path, Boolean caseSensitive)
3>     at UXDivers.Daas.Commands.GrialAnalyzeSolutionCommand.FindAppXaml(IProjectItems project, IXamlManager xamlManager)
3>     at UXDivers.Daas.Commands.GrialAnalyzeSolutionCommand.Execute(IExecutionContext ctx)'
3>  [Grial] Terminating Syncrhonization
3>Done executing task "PropagateThemeTask".
3>Done building target "GrialTheme" in project "MyProjectApp.iOS.csproj".
```

**Comment by LeoHere** [comment]
Did you used the exact names I mentioned above? 

The output you should get as soon as you added the `Themes.json` with the content said above is as follows...

~~~
  Using "PropagateThemeTask" task from assembly "..../source/packages/UXDivers.Artina.Shared.2.7.5/build/netstandard1.0/UXDivers.Grial.Build.Tasks.dll".
  Task "PropagateThemeTask"
    [Grial] Initiating Syncrhonization for project '..../source/iOS/Grial.iOS.csproj'. Any Theme sync issues will be reported as a Build Warning. 
    Loading Settings from '..../source/iOS/Themes.json'
     - AppXamlPath was set
     - AppXamlProjectPath was set
     - GrialThemePath was set
    Project '..../source/iOS/Grial.iOS.csproj' was recognized as an iOS Project.
    Skipping App.xaml lookup. Using user defined App.xaml value '..../source/Grial/App.xaml'.
    Skipping App.xaml Project lookup. Using user defined value '..../source/Grial/Grial.csproj'.
    App.xaml: ..../source/Grial/App.xaml
    App.xaml Project: ..../source/Grial/Grial.csproj
    Skipping Theme lookup. Using user defined value '..../source/Grial/Themes/GrialLightTheme.xaml'.
    Loaded theme colors from '..../source/Grial/Themes/GrialLightTheme.xaml'.
    iOS theme color synchronization completed (..../source/iOS/ThemeColors.cs).
    [Grial] Terminating Syncrhonization
  Done executing task "PropagateThemeTask".
~~~

Please notice that:
1. `AppXamlPath`, `AppXamlProjectPath`, `GrialThemePath` are set.
2. there is no "Initiating App.xaml lookup."

In the last log output you attached only `GrialThemePath` is set.  The other two have a different name.

BTW. You will need to add this file to your Android project too.

**Comment by RocketPop** [comment]
Ah, I see the issue with what I did. I found out about Themes.json here: http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-theme-and-branding-of-your-app-advanced-theme-synchronization-configuration - and it has different key names. Note the sample from that documentation: 
```
    {
        "ThemeSyncEnabled": true,
        "AppXamlFullPath": null,
        "AppXamlProjectFullPath": null,
        "iOSColorsFileName": "ThemeColors.cs",
        "AndroidColorsFile": "Resources\\values\\Colors.xml",
        "iOSColorsNamespace": null,
        "ThemesFolder":"Themes"
    }
```
I used those incorrect keys rather than reading your example more carefully 😀 Using your actual key values it does now sync the colors. I'll push that over into my Android project as well. Thanks! This will be just fine a workaround for now. If you want I can create a separate issue for the incorrect key names in that documentation.

**Comment by LeoHere** [comment]
@RocketPop ok cool. No need to open a new issue for this. Once we fix the docs we will close this issue. Thanks

**Comment by jpbrocca** [comment]
@RocketPop thank you very much for your help! 
I have fixed the issue in the documentation.

I am closing this bug now.
Feel free to re-open as needed.

Best regards and again thanks,
JP

**Comment by RocketPop** [comment]
So just a reminder - without the Themes.json, the netstandard project does not refresh the theme colors / generated files - so the initial problem is still there :)

**Comment by LeoHere** [comment]
@RocketPop actually, .NET Standard projects should work fine out of the box. I think there is something in your big app we don't support quite well. If possible, can you share with me the `csproj` and `sln` of your solution. Just those files not the actual code. If that is an option, please send it to l r o d r i g u e z at uxdivers.com.

**Comment by RocketPop** [comment]
Sure. Give me a little while and I'll email those over.
