### ISSUE TITLE
Xamarin Forms v 4.0 breaking changes iOS

### ISSUE THREAD

**Issue by southrock70** [UXDivers/Grial-UI-Kit-Support#526]
The new Xamarin Forms version 4.0 does not work with UXDiver GrialKit

### Description
I have a project that IS using Xamrin Forms v4.0 and UXDivers.Artina 2.7.6RC
I want to use the new Xamarin Shell function.

I have tried these version of Xamarin Forms:
4.0.1.102444-nightly
4.0.0-pre4
4.0.0-pre3
And these verions of UXDrivers.Artina:
2.7.6RC
2.7.5

In all above I got a compilation error for iOS, Android works fine.
Can't resolve the reference 'System.Void Xamarin.Forms.Platform.iOS.VisualElementTracker::.ctor(Xamarin.Forms.Platform.iOS.IVisualElementRenderer)', referenced from the method 'System.Void UXDivers.Artina.Shared.ArtinaPhoneMasterDetailRtlAwareRenderer::ViewDidLoad()' in 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.

### Steps to Reproduce

1.  Make new project and get Nuget package for Xamariin Forms v 4.0
2.  Init Shell in appdelegate.cs             // Initialize Xamarin Shell
            global::Xamarin.Forms.Forms.SetFlags("Shell_Experimental");

3.  Build, and you get error.

### Expected Behavior
Build with out error.

### Actual Behavior
Build error as decribed above

### Basic Information

- Version with issue: 2.7.5, 2.7.6RC Xamarin Forms v.4.0
- Last known good version: Xamarin Forms <=v3.5
- IDE: Visual Studio 2017 15.9.7

### Screenshots
N/A

**Comment by obsf** [comment]
Hi, 

i just had the same error after a general update of the project packages.

I am now on the xamarin.forms v3.5.0.129452 and getting this error:

Error MT2101: Can't resolve the reference 'System.Void Xamarin.Forms.Platform.iOS.VisualElementTracker::.ctor(Xamarin.Forms.Platform.iOS.IVisualElementRenderer)', referenced from the method 'System.Void UXDivers.Artina.Shared.ArtinaPhoneMasterDetailRtlAwareRenderer::ViewDidLoad()' in 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101).

**Comment by dirivero** [comment]
Hi,
This should fix it: https://github.com/xamarin/Xamarin.Forms/pull/5281

**Comment by southrock70** [comment]
I can confirm it now builds with Xamarin.Forms 4.0.1.184172-nightly

**Comment by jbtamaresgit** [comment]
Seems like I can still reproduce this issue on Xamarin.Forms v3.5.0.169047.
UXDivers.Artina v2.7.5
Is there a need to upgrade to 4 for it to be fixed?

**Error:**
`Can't resolve the reference 'System.Void Xamarin.Forms.Platform.iOS.VisualElementTracker::.ctor(Xamarin.Forms.Platform.iOS.IVisualElementRenderer)', referenced from the method 'System.Void UXDivers.Artina.Shared.ArtinaPhoneMasterDetailRtlAwareRenderer::ViewDidLoad()' in 'Xamarin.Forms.Platform.iOS
`

**Comment by dirivero** [comment]
Another option is to temporary downgrade to 3.4 and wait a few days until the next release of 3.5 that will include that fix.

**Comment by samhouts** [comment]
We'll be releasing that fix in Xamarin.Forms 3.6 (stable!) and 4.0.0-pre6 next week. Thanks for your patience!
